Zicht\Bundle\UrlBundle\Entity\UrlAlias:
    constraints:
            -
                Zicht\Bundle\UrlBundle\Validator\Constraints\ContainsUrlAlias: ~
    getters:
        publicUrl:
            -
                Regex:
                    pattern: '~^/~'
                    message: 'The public url must start with a slash'